// Every experiment, in order, with what was tested, what was found, and why that finding led to the
// next one. Pulled directly from docs/expNN_*.md — nothing paraphrased beyond tightening for bullets.
export const PHASES = [
  {
    name: "Phase 1 — build the frozen architecture",
    range: "Exp 0–33",
    experiments: [
      { n: "0", title: "Dataset validation + EDA", q: "Is the dataset internally consistent, and free of leaked answers?", found: "0 critical errors across 50 integrity/leakage checks; confirmed the dataset had been hardened 3 rounds so decision-critical facts live only in free text.", next: "Dataset trustworthy — safe to start building baselines against it." },
      { n: "1", title: "End-to-end sanity (smallest first version)", q: "Can a claim + its correct clauses become a schema-valid decision, end to end?", found: "18/18 outputs schema-valid, 0 errors, on the pre-hardening dataset. This is the project's required smallest slice — feasibility only, not a performance claim.", next: "Pipeline works end to end. Safe to add the first real baseline: deterministic rules." },
      { n: "2", title: "Deterministic rules baseline", q: "Do plain rules, reading structured fields, solve this?", found: "Collapsed once facts moved into free text across 3 hardening rounds (70/70 → 48/70 on the regex baseline) — this is the project's own before/after leakage test.", next: "Rules alone can't survive hardened free text. Needs either better extraction or a different source of grounding — try a generic LLM next to see the opposite failure mode." },
      { n: "3", title: "Generic LLM, no policy", q: "Does the model already know the policy well enough without retrieval?", found: "Confident, unsupported answers — no grounding in the actual corpus.", next: "The model needs real policy text. Before building RAG, check whether the whole corpus just fits in context." },
      { n: "4A/4B", title: "Long-context feasibility + baseline", q: "Is the 22-document corpus small enough to skip retrieval entirely?", found: "Feasible, but ~40x the cost of tuned RAG per claim, with no accuracy gain (31.4% vs. RAG's eventual ~31%).", next: "Long context doesn't beat retrieval and costs far more — RAG is justified. Start tuning it." },
      { n: "5", title: "Naive RAG baseline", q: "Does basic retrieval beat no-policy-at-all?", found: "300/50 chunking, top-3, raw query — 30.0% accuracy, better grounded but still weak; voyage-4-lite was the best of 4 embedding models compared.", next: "Retrieval helps a little; now tune each retrieval parameter one at a time, starting with chunk size." },
      { n: "6", title: "Chunk size and overlap", q: "Does poor chunk boundary placement explain the weak retrieval?", found: "Tested 150/25, 300/50, 600/100, 900/150 — recall rose with larger chunks; froze 600/100 as the best recall/cost trade-off.", next: "Chunking fixed. Now tune how many chunks to retrieve (top-K)." },
      { n: "7", title: "Top-K sensitivity", q: "Where does K trade recall for distractors and cost?", found: "K=1,3,5,8 tested; recall kept climbing through K=8 (0.52) without a clear plateau yet, but cost/distractor risk rises too.", next: "K=8 frozen as the practical stopping point. Now test whether a different retriever type recovers more evidence." },
      { n: "8", title: "BM25 vs. dense vs. hybrid retriever", q: "Can keyword or hybrid retrieval recover evidence dense retrieval misses?", found: "Dense alone (0.52 recall@8) beat both BM25 (0.295) and hybrid RRF (0.436) outright.", next: "Dense retrieval frozen. Now test whether filtering by date/region/doc-type improves precision." },
      { n: "9", title: "Metadata filtering (M4)", q: "Does filtering by date/region/document-type reduce wrong-version and wrong-region answers?", found: "M4 filter frozen — the full tuned retrieval config (600/100, K=8, dense, M4) reaches this project's retrieval ceiling.", next: "Retrieval is now as good as it's going to get on its own terms. Test whether that's actually the bottleneck at all, with a policy oracle." },
      { n: "10", title: "Query rewrite", q: "Does rewriting the query before retrieval help?", found: "Improved retrieval metrics but made final answers worse — an early first sign that retrieval quality and decision quality don't move together.", next: "Not adopted. Confirms the need to directly test retrieval-vs-reasoning as separate questions — Exp 11." },
      { n: "11", title: "Policy oracle", q: "If retrieval were perfect, how much would accuracy improve?", found: "Handing the model the exact correct clauses moved accuracy only from 22 to 25/70 — retrieval was not the dominant downstream bottleneck.", next: "The bottleneck is reasoning, not retrieval. Stop tuning retrieval further; start moving mechanics (arithmetic, dates, duplicates) into code instead." },
      { n: "12 / 12B", title: "Hybrid rules + RAG; selective-router probe", q: "Does pulling arithmetic/date/duplicate logic into code, and routing only genuine ambiguity to the LLM, help?", found: "Hybrid reached 47.1% (up from ~31%); the router probe (12B) confirmed a deterministic-first design beats blind LLM adjudication and beats blind escalation.", next: "The routing concept works. Now qualify each remaining component (missing-info, duplicates, enterprise facts, tools) one at a time before assembling the final architecture." },
      { n: "13", title: "Missing-information detection", q: "Can any system ask for exactly the missing field, not just \"more info needed\"?", found: "RAG-based approaches scored 0.0 field precision/recall — a real vocabulary-drift problem, not formatting. The deterministic path inherited its own vocabulary correctly 14/16 times.", next: "Prefer the deterministic field name when available; treat an LLM-only field name as a lower-confidence hint. Move to duplicate detection." },
      { n: "14", title: "Duplicate detection", q: "Can the system separate exact/possible/legitimate-repeat/split without false-blocking a legitimate repeat?", found: "14A/14B (exact + fuzzy deterministic): perfect, 0% false-block rate. 14C (LLM-assisted on ambiguous cases): not evaluable — only 3 POSSIBLE_DUPLICATE cases exist in the whole dataset.", next: "14A/14B carried forward as-is. 14C's real evaluation deferred to a split that actually contains the class. Move to split-transaction detection." },
      { n: "15", title: "Split-transaction detection", q: "Does the full split-transaction chain (retrieval, grouping, combined amount, policy consequence) work, not just the label?", found: "4/4 on every sub-step, including correctly using region-specific local-currency thresholds for India/Japan combined amounts.", next: "No change needed (small-n, stated as a raw count, not a rate). Move to testing whether the LLM even needs enterprise facts pre-resolved." },
      { n: "16", title: "Enterprise-evidence oracle", q: "Does the LLM need enterprise facts pre-resolved, or can it interpret raw records itself?", found: "29% of evidence-dependent claims were solved only once facts were resolved, not merely supplied — direct evidence Exp 12's gain was interpretation, not data access.", next: "Tools should return resolved facts and validity flags, not raw rows for the model to interpret. Build and test that tool layer next." },
      { n: "17", title: "Typed enterprise tools", q: "Does the tool layer work reliably and return validated facts, not raw rows?", found: "All 22 tool unit tests passed, including a full validate_approval fixture matrix; a DELEGATED approval that looks fine on its raw row was correctly flagged DELEGATION_INVALID once the delegation record itself was checked.", next: "Tool layer qualified. Time to assemble a full fixed workflow using it." },
      { n: "18", title: "Fixed workflow", q: "Does a pre-declared, model-free tool sequence handle enterprise-evidence cases well, including the hardest agent-candidate claims?", found: "Highest raw accuracy of any system yet (64.3% dev) — but 13.5% FAR, unsafe.", next: "Accurate but unsafe. Before building an agent, audit whether any claim genuinely needs dynamic tool choice at all — Exp 19." },
      { n: "19", title: "Agent-necessity audit", q: "Do the hardest claims actually need a model deciding what to look up next, or does a fixed sequence already solve them?", found: "7 of 13 \"agent-candidate\" claims were already solved by the purely static workflow — the failures traced to specific implementation gaps, not to needing dynamic tool choice.", next: "Some claims may still need dynamic choice. Test a real bounded agent on the same 13 to see if it actually adds value — Exp 20." },
      { n: "20", title: "Bounded agent pilot", q: "Does a real ReAct agent beat the fixed workflow on the hardest 13 claims?", found: "Exact tie (7/13 each) but on different, complementary cases — together they solve 11/13 — while the agent was 3x less safe (30% vs. 10% FAR).", next: "Complementary errors argue for a selective architecture, but the agent alone isn't safe yet. Move to adversarial guardrail testing before freezing anything." },
      { n: "28", title: "Guardrail suite (security)", q: "Does the system survive prompt injection, fake authority, conflicting records, and tool/schema abuse?", found: "Found and fixed a real bug (conflicting approval records silently read the first match); retrieval-text injection fully succeeded once and was logged as a disclosed, unfixed risk.", next: "One bug fixed, one risk accepted and disclosed. Quantify how well the system knows when to abstain before freezing the architecture." },
      { n: "29", title: "Abstention / escalation quantification", q: "Does abstaining (escalating) earn its cost, or is it just deferral?", found: "Escalate-everything-unresolved was \"safe but useless\" (65.7% human review rate); LLM-on-residual fixed 7/18 genuine errors while wasting only 1 review — the better trade.", next: "This exact pattern — deterministic where conclusive, LLM only for the residual, human review reserved for genuine escalations — is the architecture to freeze. Build and compare it formally in Exp 30." },
      { n: "30", title: "Architecture freeze", q: "LLM-for-everything vs. fixed workflow vs. the selective design — which actually wins on safety, not just accuracy?", found: "Selective design: 0/52 falsely approved (0% FAR) at 61.4% dev accuracy, giving up a few points versus the workflow's 64.3%/13.5% FAR.", next: "This is the architecture. Confirm its cost is negligible, then run the one-shot official test." },
      { n: "31", title: "Cost-to-serve", q: "Is AI inference cost a material constraint on this design?", found: "$0.00043/claim — negligible at any realistic scale; human review is the dominant, controllable cost lever instead.", next: "Cost is a non-issue for this design. Time for the one-shot, hash-manifest-verified final test." },
      { n: "32", title: "Frozen final test (one-shot, official)", q: "How does the frozen design perform on 50 claims it has never seen, touched exactly once?", found: "30/50 (60%), 0/37 falsely approved. Deterministic path generalized perfectly (22/22); the LLM-residual path never once correctly predicted APPROVE (0/13).", next: "This is the official result — it cannot be re-earned. Diagnose exactly why the residual path failed before touching anything further." },
      { n: "33", title: "Failure analysis", q: "What actually caused all 20 residual-path errors?", found: "Manual classification (not a keyword classifier, per Exp 19's lesson): 7 policy-reasoning errors, 5 missing-info confusion, 4 resolved-fact errors, 0 retrieval errors — every relevant clause was present in the retrieved evidence.", next: "Retrieval is conclusively not the problem. See if a genuinely dynamic agent, searching and re-searching, can fix the reasoning instead." },
    ]
  },
  {
    name: "Phase 2 — try a better agent, and rule things out",
    range: "Exp 34–39",
    experiments: [
      { n: "34", title: "Agentic RAG rebuild", q: "Does giving the model real search-and-re-search ability fix the reasoning failures?", found: "Worse than the fixed workflow (4/13) — repeated the same \"ignores a given fact\" failure, using the wrong hotel ceiling on a Chennai claim.", next: "Autonomy alone made it worse. Isolate exactly which layer (prompt, model, tool interface) is responsible." },
      { n: "35", title: "Prompt / model / tool-interface isolation", q: "Which single layer, fixed in isolation, actually helps?", found: "A stricter prompt tripled false approvals; a 16x pricier model matched accuracy with worse safety; a better tool interface only helped when the model chose to use it.", next: "None of the obvious levers work alone. Try fixing a specific mechanical bug (tier substitution) plus running tool calls in parallel." },
      { n: "36", title: "Parallel tool calls + poka-yoke ceiling fix", q: "Does fixing the one identified ceiling bug, plus parallelizing tool calls, help overall?", found: "The targeted bug fix worked for its one case, but no overall improvement — and step-cap hits got worse (8/13).", next: "Still no overall gain. Go back to the retrieval-vs-reasoning question directly, this time on the agent architecture — repeat the oracle test." },
      { n: "37", title: "Perfect policy oracle (diagnostic, on the agent)", q: "If the agent had perfect policy evidence, would it finally decide correctly?", found: "Same accuracy, but false approvals nearly quadrupled — perfect evidence was insufficient to resolve the agent's decision failures.", next: "Evidence quality is ruled out a second time. Directly audit what the agent's own searches are actually retrieving — Exp 38." },
      { n: "38", title: "$0 RAG trace audit", q: "What is the agent's own search behavior actually achieving?", found: "Mean recall of required clauses: 33.6% — genuinely weak, and 0 of 13 cases ever issued a second search, despite being told to when needed.", next: "This is a real, separate retrieval problem worth fixing on its own terms — but the prior findings say fixing it alone probably won't fix accuracy. Test that directly." },
      { n: "39", title: "True two-hop RAG + poka-yoke", q: "Does fixing the diagnosed retrieval gap (forced governance retrieval + a concrete re-query trigger) actually raise accuracy?", found: "Recall rose from 33.6% to 45.4%, and re-querying rose from 0/13 to 7/13 — the retrieval fix worked exactly as designed. Accuracy still fell, and false approvals roughly doubled.", next: "Retrieval and reasoning are now confirmed as two separate, independently real problems — and better evidence alone cannot fix a reasoning bottleneck. Stop iterating on retrieval and autonomy; change what the model is asked to do at all." },
    ]
  },
  {
    name: "Phase 3 — stop asking the model to decide, close the gap",
    range: "Exp 40–52",
    experiments: [
      { n: "40", title: "Decision-in-code", q: "What if a tool computes the decision in code instead of just fetching facts?", found: "Ties the fixed workflow (7/13) at 0% FAR — the first agent variant to match the workflow's safety.", next: "The mechanism works. Add a gate so the model can't override a tool that already has the right answer." },
      { n: "41", title: "Disposition gate", q: "If a tool already computed the correct disposition and the model disagrees, should the tool win?", found: "Beats the fixed workflow outright (9/13) at 0% FAR — the model had ignored a correct signal on 3/5 delegation cases.", next: "The gate is the real fix. Extend the tool set to close the next known gap (project-budget claims)." },
      { n: "42", title: "+ project-budget tool (unguarded)", q: "Does adding a tool for the last known gap (CIRC-26-02) help without breaking anything?", found: "Same accuracy, but a live regression: the new tool fired on 2 hotel claims it was never built for, both overridden to an incorrect ESCALATE.", next: "An ungated tool answering the wrong question is exactly as harmful as bad model reasoning. Add domain guards so each tool checks its own applicability first." },
      { n: "43", title: "Guarded tools, corrected", q: "Does adding domain guards (check the claim type before answering) fix the Exp 42 regression?", found: "11/13 (84.6%) — the best result on this slice so far. The one remaining error found live was a documentation gap, corrected on inspection, not a new bug.", next: "Confirm this holds on validation data never touched before, and close the one remaining known gap." },
      { n: "44", title: "Full confirmation on dev + validation", q: "Does this design generalize to validation claims it has never seen?", found: "17/19 (89.5%), 0% FAR — but this was the best result on the narrow C_AGENT_DYNAMIC slice it was built for, not yet tested beyond it.", next: "Try a stronger model to see if it closes the remaining gap, and separately test extending the whole pattern to the rest of the dataset." },
      { n: "46", title: "+ stronger model (gpt-4o)", q: "Does a more capable model improve the guarded design further?", found: "Worse accuracy (15/19 vs. 17/19) at 30x the cost — FAR held at 0% by the guards regardless of model.", next: "Bigger models don't help this architecture. The real test is scaling the pattern to the full dataset — Exp 45." },
      { n: "45", title: "Full-dataset extension", q: "Does the guarded-tool pattern hold when applied to every claim, not just the family it was built for?", found: "Accuracy jumped (51/70) but safety broke — FAR rose to 11.5%, every false approval in a category with no guarded tool.", next: "The pattern needs a guarded tool (or an equally-safe fallback) for every category before it can be trusted dataset-wide. Try reusing existing, already-tested code as a fallback first." },
      { n: "47", title: "Workflow-reuse fallback (denylist)", q: "Can the already-tested fixed-workflow code safely act as a catch-all for categories with no dedicated tool?", found: "Made it worse (46/70, down from 51/70) — that code shares the same fragile free-text parsing every other fix in this arc exists to route around.", next: "Reusing tested code isn't automatically safe if it depends on the same fragile inputs. Redesign the fallback to trust only checks that never touch free text." },
      { n: "48", title: "Allowlist redesign", q: "Does trusting only free-text-independent checks (duplicates, submission window, merchant, documentation) fix the regression?", found: "45/70, FAR down to 3.9% — the safest full-dataset number yet, at the cost of giving up some accuracy.", next: "Recover the accuracy given up by building dedicated, domain-guarded tools for the categories left out." },
      { n: "49", title: "+ ground-transport tool", q: "Does a dedicated tool recover the ground-transport category safely?", found: "Live-tested: the model passed the literal string \"unknown\" for a missing field, defeating a truthiness check — 40/70 before the fix was found and corrected.", next: "One more real bug closed. Keep adding dedicated tools for the remaining categories." },
      { n: "50", title: "+ gift tool, hotel-date fix, merchant-metadata check", q: "Can three more scoped fixes close most of the remaining gap?", found: "43/70, FAR down to 1.9% (one false approval) — including catching the model miscounting hotel nights from a stated date range.", next: "One false approval left. Confirm the fix and re-run the full set cleanly." },
      { n: "51", title: "Dev confirmed clean", q: "With the last bug fixed, does a fresh full run confirm 44/70 at 0% FAR?", found: "44/70 (62.9%), 0/52 falsely approved — one better than the frozen baseline's own dev number, verified by diffing every changed prediction individually.", next: "Dev is clean. This design has never touched validation — run it there for the first time." },
      { n: "52", title: "Validation run + 7th bug found", q: "Does this design hold on validation, the first time it has ever seen that split?", found: "Found a 7th real bug live — check_hotel_compliance never verified an approved travel request existed. Fixed, then both splits re-confirmed: 44/70 dev, 21/30 validation, 0% FAR on both.", next: "This is the final candidate state — but its own design was shaped by what this validation run revealed, so it is a development-and-validation-selected candidate, not an independently validated one. A cost analysis (not a new experiment number) is what actually decided whether to ship it." },
    ]
  },
  {
    name: "Phase 4 — root-cause the APPROVE blind spot, fix it, then actually test it on fresh data",
    range: "Exp 53–60",
    experiments: [
      { n: "53", title: "Approve-calibration prompt fixes", q: "Can prompt-only changes recover the guarded candidate's near-zero APPROVE recall?", found: "Recovered some real approvals, but introduced a new false approval in the process — a straight accuracy-for-safety trade this project's own standing rule rejects.", next: "Prompting alone isn't safe. Try a stronger model instead of a different prompt." },
      { n: "54", title: "Stronger model on the same prompt", q: "Does swapping in a stronger model (gpt-4o) fix APPROVE recall without a prompt rewrite?", found: "Barely helped, and the model still directly contradicted its own correct arithmetic in the same response.", next: "The model isn't the bottleneck either. Test whether just handing the system the correct facts changes anything." },
      { n: "55", title: "Hand the frozen resolver the correct facts directly", q: "If every missing/wrong fact is corrected by hand, does the frozen resolver's decision change?", found: "0 of 5 hand-corrected cases changed the final decision. The resolver ignores facts it's given unless something in the architecture enforces their use.", next: "Facts alone don't help — something has to force the decision to use them. Try wiring the same fix into the guarded agent's gated tool layer instead." },
      { n: "56", title: "Hotel-ceiling fix, wired into the disposition gate", q: "Does the same fact-correction work when enforced by the guarded agent's existing disposition gate, instead of just handed to the model?", found: "First real win: 13/18 → 16/18 on hotel cases, 0 new false approvals.", next: "Confirm the gate itself is what mattered, not just the fix, by removing the gate and repeating the identical fix." },
      { n: "57", title: "Identical fix, gate removed", q: "Does the Exp 56 fix still work with the enforcing gate taken away?", found: "0 change — proof the disposition gate is what makes the fix work, not the underlying fact-correction alone.", next: "Extend the gated-fix pattern to every other category with the same blind spot." },
      { n: "58", title: "Gated fixes extended to mileage + software, full 70-case dev run", q: "Does the gated-fix pattern generalize when extended to mileage and software compliance across the whole dev split?", found: "55/70 → 59/70, APPROVE recall 11/18 → 15/18, false approvals unchanged at 2/52 (pre-existing, not caused by this fix). Disclosed caveat: this run's own 55/70 baseline doesn't match the previously documented official dev baseline (44/70) — a different, harder baseline configuration than Exp 51/52's.", next: "Keep extending the pattern to the remaining categories (airfare, training, evidence-consistency, gift-recipient) to close the rest of the gap." },
      { n: "59", title: "Gated fixes extended to every remaining category", q: "Does finishing the pattern across every remaining gap close the rest of the APPROVE blind spot?", found: "55/70 → 67/70, APPROVE recall 11/18 → 18/18 (every real approvable dev case now resolves correctly), false approvals cut from 2/52 to 1/52.", next: "This candidate has now only ever been measured on data its own fixes were built against. Test it on a genuinely fresh, independently-labeled holdout before trusting it generalizes." },
      { n: "60", title: "Fresh, independently-labeled 50-case holdout", q: "Do the Exp 53–59 fixes generalize to 50 cases neither architecture has ever seen, labeled by a genuinely separate reference implementation?", found: "Frozen resolver: 22/50 (44%), still 0/20 APPROVE recall ever. Fixed candidate (gpt-4o-mini): 34/50 (68%), 12/20 APPROVE recall, 0% FAR — matches the frozen design's safety bar at roughly double its accuracy. A stronger model (gpt-4o) reached 39/50 but introduced 2 false approvals (6.7% FAR) — more accurate, less safe. Reframed by safe-automation rate: the frozen resolver's 0% FAR hides that it wrongly blocks 40% of real approvable claims on this data; the fixed candidate cuts that to 4%.", next: "The fixed candidate is the leading development candidate with real fresh-data evidence behind it — not an independently validated replacement for the frozen architecture, and not claimed as one. A formal, pre-registered freeze-and-larger-holdout is what would actually be needed before calling it final." },
    ]
  },
  {
    name: "Phase 5 — pre-register the candidate and test it a second, independent time",
    range: "Exp 61",
    experiments: [
      { n: "61", title: "Pre-registered freeze (\"Selective Automation V3\") + a second, independent 30-case holdout", q: "Does a 0% observed false-approval rate survive a second test, pre-registered with Exp 32-grade rigor before any holdout case was generated?", found: "A freeze manifest (experiments/v3_freeze_manifest.yaml) named and pinned the exact candidate architecture before any of 30 new cases were generated. Pass-1 ground-truth review caught 5 of my own case-design bugs (grade-band mismatches, a reworded note that accidentally tripped a conflict check) before any model was run. Result: frozen resolver 11/30 (36.7%), still 0/15 APPROVE recall ever, 0% FAR. Candidate: 20/30 (66.7%), 9/15 APPROVE recall, but 1/15 false approvals (6.7% FAR) — its first observed false approval on fresh data. Traced live: the require-tool gate worked correctly (the tool was consulted), but check_gift_compliance's free-text parsing did not recognize \"a prepaid e-voucher redeemable at various outlets\" as a cash-equivalent gift.", next: "No fix was applied, per the manifest's own process rule — documented as a finding for a future experiment. Combined across Exp 60 and Exp 61, the candidate's observed false-approval rate is 1/45 (~2.2%), not 0%. The candidate remains the leading development candidate, now described with a materially more honest statement of its residual risk." },
    ]
  }
];

// Flat list of every experiment entry, independent of how PHASES groups them above -- the Project
// Story tab groups these into its own 7-phase presentation structure instead.
export const ALL_EXPERIMENTS = PHASES.flatMap((p) => p.experiments);
