"""Writes experiments/exp32_freeze_manifest.yaml with SHA-256 hashes of every frozen file (computed, never typed)."""
import hashlib, json, sys, time
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
FROZEN = ["src/config.py", "src/tables.py", "src/rules.py", "src/history.py", "src/tools.py", "src/workflow.py", "src/router.py", "src/flags.py", "src/policy.py", "src/chunking.py",
          "src/embed.py", "src/retrieval.py", "src/retrievers.py", "src/llm.py", "src/llm_exp.py", "src/rag_run.py", "src/evaluate.py", "src/metrics.py"]
h = lambda p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest()
D = ROOT / "ExpenseGuard_FINAL_CURRENT_DATASET"
txt = f"""# Exp 32 freeze manifest. Generated by scripts/make_freeze_manifest.py on {time.strftime('%Y-%m-%d %H:%M')}.
# Commit this file BEFORE the final run. scripts/exp32_final_test.py refuses to run if any frozen file below differs from its hash.
experiment: EXP32_FINAL_TEST
split: FINAL_TEST (40 cases, 10 independent challenge cases); run once
dataset_sha256sums_file_hash: {hashlib.sha256((D / 'SHA256SUMS.txt').read_bytes()).hexdigest()}

primary_system: selective router (rules for claim-only claims, fixed tool workflow for hotel, software and prior-expense claims); no LLM, no agent
baselines_run_once_for_comparison:
  - rules only (Exp 2)
  - gpt-4o-mini RAG + code facts (openai/gpt-4o-mini, temperature 0, dense voyage-4-lite, recursive 300/50, K=3, metadata filter)
  - llama3.2:3b RAG + code facts (same retrieval and prompt)
not_run: agent (Exp 19 audit: not justified); Exp 10, 20-27

decisions_recorded_before_the_run:
  hotel_over_ceiling_no_exception_no_conference: ESCALATE (GEP26-4.1). Changed from REJECT after seeing 3 development/validation labels; those splits are therefore no longer independent for this branch.
  currency_threshold_ambiguity: no logic change; policy-faithful FX-equivalent thresholds kept. Cases are flagged by inputs only (src/flags.py) and reported separately.
  invented_rules: none. The project-status hotel rule was removed in Exp 18 v2.

metrics_reported:
  - Correct Disposition Rate with raw count and 95% Wilson interval, all 40 cases
  - False approvals among non-approvable cases; Human Review Rate; median and P95 latency; cost per case
  - the 10 challenge cases separately
  - currency-flagged cases separately, and the result excluding them
  - Exp 33 failure categories for every incorrect prediction of the primary system

budget: MAX_BUDGET_USD 3.50; projected final-run spend under $0.02

frozen_files_sha256:
""" + "\n".join(f"  {p}: {h(p)}" for p in FROZEN) + "\n"
(ROOT / "experiments" / "exp32_freeze_manifest.yaml").write_text(txt)
print(txt)
